### ISSUE TITLE
Log request headers and body at 4xx level when response status is >= 400

### ISSUE THREAD

**Issue by KSD-France** [Rhumbix/django-request-logging#104]
Hello, and thanks for the good work! We use and love your package but we do have one problem with it.

We would definitely like to have headers and body of failing requests (status >= 400) to be logged at the level set in `settings.REQUEST_LOGGING_HTTP_4XX_LOG_LEVEL`.

# Current behavior

```py
class LoggingMiddleware(object):
    def __call__(self, request):
        self.process_request(request)
        response = self.get_response(request)
        self.process_response(request, response)
        return response
```

The middleware:

1. Logs incoming request.
2. Lets the response be processed by Django.
3. Logs the response.

This design makes it impossible to log request headers/body at different levels depending on response status code, because, well, response does not exist yet at the time.

# Proposed behavior

Logging both request AND response after response has been processed, allowing customization of log level on both the request and its response.

We would happily offer a pull request for this change :-)

**Comment by tclancy** [comment]
Would be happy to have the PR, thanks!
