### ISSUE TITLE
[Questions] Is it okay to send a PR with following features?

### ISSUE THREAD

**Issue by calvin620707** [Rhumbix/django-request-logging#11]
Hi there,

I tried to use this package in our django server, but I need some customizations. I can tried to help to implement those features and send a PR. However, I just want to confirm if those features is acceptable for you~?

**Features**
1. Use Django settings to change default log level from DEBUG to another level
Reason: May root logging handle set logging level to INFO and it looks like those logs in DEBUG level won't appear in my log file. Therefore, I need a setting to change default log level to INFO.
2. Use Django settings to disable colorize
Reason: We didn't need ANSI graphics codes in log file.

**Comment by kennethjiang** [comment]
They look reasonable. I'd like the keep current behavior as default when these settings are absent, unless you have a good reason why the default should change.

**Comment by calvin620707** [comment]
@kennethjiang I have sent a PR. Current behavior as default. Feel free to let me know if any questions or any changes are needed~ 

BTW, when will this package be updated to pypi? I checked on pypi and the latest version is [0.4.6](https://pypi.python.org/pypi/django-request-logging/0.4.6) which be uploaded on 2016-06-20.

**Comment by kennethjiang** [comment]
Just merged and uploaded it to Pypi. :)
