### ISSUE TITLE
Travis CI support

### ISSUE THREAD

**Issue by pdaw** [Rhumbix/django-request-logging#16]
As they say, to test and deploy with confidence :)

**Comment by kennethjiang** [comment]
I'd love to have Travis CI integration. However I'm so tied up with work these days. If you can help me with it that'd be awesome! :) Otherwise I will get to it at a much later point...

**Comment by kennethjiang** [comment]
Thanks @pdaw

**Comment by meschbach** [comment]
First build is at https://travis-ci.org/Rhumbix/django-request-logging/builds/261927663!
