### ISSUE TITLE
Import Error MiddlewareMixin

### ISSUE THREAD

**Issue by ChristfriedBalizou** [Rhumbix/django-request-logging#18]
Django==1.8
django-extensions==1.7.8

ImportError: cannot import name MiddlewareMixin

**Comment by tclancy** [comment]
It looks like this dropped compatibility for 1.8 with #6. You should be able to get this working by specifying `==0.4.5` or pinning to 5cec9103a891e03278b9cd531733101e5010a488.

**Comment by ChristfriedBalizou** [comment]
Hello @tclancy 
Can you add a try catch arround import django.utils.deprecation.MiddlewareMixin on ImportError add the ==0.4.5 as MiddlewareMixin.

I actually implemented my own middleware but I'll make a pull request to you to fix the issue sooner.

**Comment by tclancy** [comment]
>add the ==0.4.5 as MiddlewareMixin.

Not sure I follow this part. What do you want me to do here?

**Comment by tclancy** [comment]
Closing for now unless there is something to be done here.

**Comment by ChrisRosales** [comment]
yes
