### ISSUE TITLE
document response logging

### ISSUE THREAD

**Issue by devkral** [Rhumbix/django-request-logging#20]
Please document in the readme that this middleware can also log responses.
I had to look up the code to see this features ( I need this feature)

**Comment by devkral** [comment]
because this way the middleware would turn up in searches.

**Comment by tclancy** [comment]
How should we rephrase "you will have intuitive and color coded request/response payload logging, for both web requests and API requests" to make it clearer?

**Comment by devkral** [comment]
agree. I just wrote my thoughts down.
