### ISSUE TITLE
Problem logging URI

### ISSUE THREAD

**Issue by math609** [Rhumbix/django-request-logging#32]
In the documentation it is stated that:
> If HTTP status code is between 400 - 599, URIs are logged at ERROR level, otherwise they are logged at INFO level.
> If HTTP status code is between 400 - 599, data are logged at ERROR level, otherwise they are logged at DEBUG level.

But when you look at the code:

```
def process_request(self, request):
        method_path = "{} {}".format(request.method, request.get_full_path())
        logging_context = self._get_logging_context(request, None)
        self.logger.log(logging.INFO, method_path, logging_context)
```

method_path should also be logged if there is an error at the ERROR level is't it?

**Comment by tclancy** [comment]
A request doesn't have an associated status code, only a response.

**Comment by math609** [comment]
I know a request does not have a status code. So there is no method to log the URI on the response with an error?

**Comment by tclancy** [comment]
I'm not clear what you're asking. In [`process_response`](https://github.com/Rhumbix/django-request-logging/blob/master/request_logging/middleware.py#L132), it appears to log the URI (in the `resp_log` value) unless I am misreading it:

```
def process_response(self, request, response):
        resp_log = "{} {} - {}".format(request.method, request.get_full_path(), response.status_code)
        logging_context = self._get_logging_context(request, response)

        if response.status_code in range(400, 600):
            self.logger.log_error(logging.INFO, resp_log, logging_context)
            self._log_resp(logging.ERROR, response, logging_context)
        else:
            self.logger.log(logging.INFO, resp_log, logging_context)
            self._log_resp(self.log_level, response, logging_context)

        return response
```

**Comment by math609** [comment]
Ho I see... But only at the info level.. If we activate the info level we now have all the requests. Shouldn't those line be more in the range of:

`
def process_response(self, request, response):
        resp_log = "{} {} - {}".format(request.method, request.get_full_path(), response.status_code)
        logging_context = self._get_logging_context(request, response)

        if response.status_code in range(400, 600):
            self.logger.log_error(**logging.ERROR**, resp_log, logging_context)
            self._log_resp(logging.ERROR, response, logging_context)
        else:
            self.logger.log(logging.INFO, resp_log, logging_context)
            self._log_resp(self.log_level, response, logging_context)

        return response
`

**Comment by tclancy** [comment]
That makes sense to me as a behavior but perhaps it should be configurable? Happy to accept a PR either way.

**Comment by math609** [comment]
Not sure how it make sense.. In the event of a _crash_ you don't know the URI that was called unless you log **all** request made.
