### ISSUE TITLE
No mean no...even for headers and responses

### ISSUE THREAD

**Issue by meschbach** [Rhumbix/django-request-logging#35]
We still log headers and responses even when a method has the annotation "no_logging".  We should probably make a request silent if that is the case.

**Comment by stardust85** [comment]
Maybe a unit test is missing? (did not check the code yet)

**Comment by tclancy** [comment]
@meschbach Is this fixed with the recent changes?

**Comment by meschbach** [comment]
It should have been closed a while ago!  Thank you for catching that.
