### ISSUE TITLE
A way to disable logging for certain attributes of payload like password

### ISSUE THREAD

**Issue by snyaggarwal** [Rhumbix/django-request-logging#38]
There should be a way to blacklist certain keywords (like password) to not logged.

**Comment by tclancy** [comment]
Is the `no_logging` decorator introduced in 798ff680ea6a0a31f211576d9bc8dc8477bf06e9 sufficient for what you want? I updated the README to mention it.

**Comment by snyaggarwal** [comment]
Well I was looking for more at attribute level and not at function level. I do want to log other parameters in payload except few like password.
like Rails has:
`Rails.application.config.filter_parameters`

is there exist something like this?

**Comment by tclancy** [comment]
Not currently and it looks like that would involve parsing the response which would add significant overhead (I think).

**Comment by snyaggarwal** [comment]
I think its not that significant effort, a filter here would do:
https://github.com/Rhumbix/django-request-logging/blob/master/request_logging/middleware.py#L160

I will raise a pull_request soon!

**Comment by tclancy** [comment]
That's a good one. Off the top of my head the only thing I can think of is monkey-patching the function by importing it into your code and wrapping it with the decorator function.

**Comment by direwolf424** [comment]
@tclancy thanks for the suggestion, i will try and let you know if it works.
