### ISSUE TITLE
400-499 responses should not be logged as ERROR

### ISSUE THREAD

**Issue by rbruggem** [Rhumbix/django-request-logging#42]
Only requests in the 500-599 represent errors.
400-499 are very legitimate response codes to use when handling error and are therefore not errors.

**Comment by tclancy** [comment]
To be pedantic, 500-599 represent server errors, while 400-499 represent client errors. I could be convinced by a PR that [changed the code here](https://github.com/Rhumbix/django-request-logging/blob/master/request_logging/middleware.py#L166) to log 4xx as `WARN`.

**Comment by stardust85** [comment]
yes, warning would be great, because it warns you that somebody uses your API incorrectly. And if the user is authenticated, you can easily track down who is it if interested

**Comment by tclancy** [comment]
@stardust85 Do you mind updating the open PR to do that as requested above? Once that's set I will merge.

**Comment by stardust85** [comment]
I can do it, but cannot promise when... Will add it to my task list...
