### ISSUE TITLE
Handling of StreamingHTTPResponses

### ISSUE THREAD

**Issue by oligond** [Rhumbix/django-request-logging#44]
Currently, the case that a response is a `django.http.StreamingHttpResponse` (instead of a `django.http.HttpResponse` doesn't seem to be covered.
This leads to an `AttributeError` in the [`LoggingMiddleware._log_resp`](https://github.com/Rhumbix/django-request-logging/blob/35ac2254d811fc7584216505ef57756856f68b8e/request_logging/middleware.py#L216) method (and a 500 Http status code) because `response.content` is accessed, but StreamingHttpResponse objects don't have that attribute, but a `stream_content` instead.
If you're generally ready to accept a PR adding proper handling of `StreamingHttpResponse`, let me know, add I'll try to put one together.

**Comment by tclancy** [comment]
That would be great, thanks!
