### ISSUE TITLE
Add support for unicode literals?

### ISSUE THREAD

**Issue by gyukebox** [Rhumbix/django-request-logging#47]
First of all, thanks for this amazing middleware!

While I was using, there were situations to log Korean request and/or response entities.  
However, I realized that this middleware logs unicode literals "as is", not decoded into its natural characters. (i.e. Korean, Chinese, etc.)

Wouldn't it be nice if I can add supports for those unicode literals?

**Comment by tclancy** [comment]
That would be great, but can you also measure the effect on performance? If it's significant, we will want to make this a setting or make it dependent on Django's [`USE_L10N`](https://docs.djangoproject.com/en/2.0/ref/settings/#use-l10n).

**Comment by gyukebox** [comment]
@tclancy I have measured performance with python cProfile, and discovered that the performance difference is under 1 millisecond.

The following is the measurement of performance as is:
<img width="1920" alt="unicode_as_is" src="https://user-images.githubusercontent.com/20885668/42451661-dccf0758-83c2-11e8-8682-f7812d40d777.png">

And the following is the measurement of performance when decoded into natural character(s):
<img width="1920" alt="unicode_decoded" src="https://user-images.githubusercontent.com/20885668/42451680-eec42c5e-83c2-11e8-9d6a-ab1f9b077a39.png">

However, I like your idea of making this feature dependent on Django settings.  
Perhaps by enabling this "unicode-decoding" feature only when `LANGUAGE_CODE` is not `en-us`?

**Comment by tclancy** [comment]
Awesome work. Let's make it dependent on `USE_L10N` as that would seem to indicate an intent to translate things.

**Comment by gyukebox** [comment]
Working on compatibility with python 2.7. Should it be compatible with python 3.7?

**Comment by tclancy** [comment]
Ideally yes, but I don't have a good way to test that right now. Is this not Python 3 compatible currently?

**Comment by gyukebox** [comment]
travis-ci/travis-ci#9815
Maybe adding python 3.7 in travis CI build?

**Comment by therefromhere** [comment]
Using LANGUAGE_CODE for this seems like a hack (eg it doesn't make sense to me that logs would be decoded if my code was en_NZ, but not if they were en_US).

I think it should be a new setting.

**Comment by tclancy** [comment]
Can we split on underscore or use `LANGUAGE_CODE[:2]` to avoid adding a setting? I am not averse to adding another setting if that won't support the typical use cases but would like to avoid this small library becoming 50% settings.

**Comment by therefromhere** [comment]
I'd fine with it being always on (or default on, with a setting to disable).

**Comment by gyukebox** [comment]
@tclancy @therefromhere 
Either way is fine. Maybe tomorrow? I can come up with PR. Thanks!

**Comment by tclancy** [comment]
That would be great. I'd say always on works for now until someone complains. Thanks again.

**Comment by gyukebox** [comment]
Should further discussion be held regarding with settings?

**Comment by tclancy** [comment]
I don’t think this requires another setting. Makes sense to just do it.

**Comment by tclancy** [comment]
Closing this as #53 should fix it.
