### ISSUE TITLE
Exclude/Include certain views for logging

### ISSUE THREAD

**Issue by andrewgy8** [Rhumbix/django-request-logging#59]
It would be nice to have a setting where a user can define which views he/she wants logged. And if they are to be logged, would it be requests, responses or both.  

For instance, we have some views which should not be logged for security reasons, so i would like to exclude them from logging the response or request.  

This could work similar to how DRF handles throttling per view. Something like:

```
LOGGING_ENABLED_FOR: {
    'customer_actions': 'response',
    'customer_auth': None,
    'customer_orders': 'request'
 }
```

**Comment by tclancy** [comment]
This should be doable via the decorator or addressed in #65

**Comment by pritstift** [comment]
@tclancy Is there any documentaion about the decorator? I would also like to exclude certain fields in the header of a request, e.g. excluding `AUTHORIZATION` header when JWTs are used

**Comment by tclancy** [comment]
There's no documentation currently, but the [decorator to block views is here](https://github.com/Rhumbix/django-request-logging/blob/master/request_logging/decorators.py) and you add it to a view method like `@no_logging("Password data hidden")`. I thought we had a way to mark POST fields as not logged/ secure data like Django itself has but it must be in a dead branch or PR.
