### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by jdavid** [Rhumbix/django-request-logging#62]
https://github.com/Rhumbix/django-request-logging/blob/master/request_logging/middleware.py#L5

The import should be reversed to avoid a deprecation warning with Django 1.11, it should read:

```python
try:
    # Django 2.x
    from django.urls import Resolver404
except ImportError:
    # Django 1.x
    from django.core.urlresolvers import Resolver404
```

Probably both try/except blocks could be merged.

**Comment by tclancy** [comment]
Awesome, do you mind combining the two import checks?
