### ISSUE TITLE
No git tag for 0.6.8 release

### ISSUE THREAD

**Issue by therefromhere** [Rhumbix/django-request-logging#68]
Thanks

**Comment by tclancy** [comment]
[Fixed](https://github.com/Rhumbix/django-request-logging/releases/tag/0.6.8), thanks.

**Comment by kennethjiang** [comment]
Sorry for missing the tag. Thank you @tclancy for your prompt action!

**Comment by tclancy** [comment]
Oh, I forgot that you released it. I think the tag is probably pointing to the wrong place, but I just made a 0.6.9 release with a tag.

**Comment by kennethjiang** [comment]
Cool. Sorry again for the confusion. I probably should have waited for you to cut a release but we were in a hurry to get the new version...
