### ISSUE TITLE
no_logging seems not to work for Class Based Views (CBVs)?

### ISSUE THREAD

**Issue by lukik** [Rhumbix/django-request-logging#81]
Can't seem to get **no_logging** to work.

I've tried as below but I still see passwords being logged. Am using **rest_framework_simplejwt** so to obtain a token I use the **TokenObtainPairView**

```
from rest_framework_simplejwt.views import TokenObtainPairView
from django.utils.decorators import method_decorator

class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

    @method_decorator(no_logging())
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
```

**Log Shows:**
2019-11-09 11:18:15 [DEBUG] b'{\n    "email": "my-email-in-full@gmail.com",\n    "password": "full-password"\n}'

**App Versions:**
django==2.2.2
djangorestframework==3.9.4
django-request-logging==0.7.0

**Comment by famousfilm** [comment]
You're not supposed to use Django's method decorator, and you didn't import the no_logging decorator. Try this.
```
from rest_framework_simplejwt.views import TokenObtainPairView
from request_logging.decorators import no_logging

class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

    @no_logging("Some reason for why we are not logging this.")
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
```
