### ISSUE TITLE
(question) is there a way to use this logger in production with uwsgi?

### ISSUE THREAD

**Issue by littlehome-eugene** [Rhumbix/django-request-logging#82]
1. Is this an ok (maybe performance wise as opposed to using uwsgi logging) to use this logger in production?

2. I can see the log in runserver but not with uwsgi setup. Is there something special I need to do see the logs in production setup (with nginx/uwsgi)

```
     'loggers': {

        'django.request': {
             'handlers': ['console'],
             'level': 'INFO',  # change debug level as appropiate
             'propagate': False,
         },

```

**Comment by tclancy** [comment]
We use it in production without issue. As for the logging, without seeing your full setup I couldn't say why you're not seeing the logs. Are you also including the middleware?
